#!/bin/sh

set -e

PARAM_ACTION=0
PARAM_NUMBER=0

while [ -n "$1" ]
do
case "$1" in
	-a)
		ACTION="$2"
		PARAM_ACTION=1
		shift ;;
	-n)
		SVNUM="$2"
		PARAM_NUMBER=1
		shift ;;
	*) echo "$1 is not an option";;
esac
shift
done

if [ $PARAM_ACTION -ne 1 ]; then
	echo "Use: $0 -a <start|stop|restart|status|update|console>"
	exit 1
fi

if [ $PARAM_NUMBER -ne 1 ]; then
	echo "Use: $0 -n <server num>"
	exit 1
fi

###########################################
#                                         #
#              USER PARAMS                #
#                                         #
###########################################

# Path to server
DIR=~/servers/l4d2_$SVNUM

# Change all Parameters to your needs.
IP="192.168.0.1"
PORT=$((27014 + $SVNUM))
PARAMS="-game left4dead2 -steam -ip $IP -port $PORT -tickrate 100 +map c1m1_hotel +mp_gamemode versus +sv_gametypes versus"

# Description for console message
DESC="Server #$SVNUM on $IP:$PORT"

###########################################
#                                         #
#           DON'T TOUCH THESE             #
#                                         #
###########################################

if [ ! -d $DIR ]; then
	echo "|"
	echo "| Error: Directory $DIR does not exists."
	echo "|"
	exit 1
fi

DAEMON="$DIR/srcds_run"
PATH=/bin:/usr/bin:/sbin:/usr/sbin

# Set core for server (1 core = 1 server)
CORENUM=$(($SVNUM - 1))

# Set screen
SCREENNUM=$((10 + $SVNUM))
SCREENNAME="L4D2_DS_$SCREENNUM"


find_server() {
	screen -ls |grep $SCREENNAME;
}

run_server()
{
	if find_server; then
		echo "|"
		echo "| $DESC: Already started!"
		echo "|"
	else
		echo "|"
		echo -n "| $DESC: Starting ... "
		taskset -c $CORENUM screen -mdS $SCREENNAME $DAEMON $PARAMS
		echo "done."
		echo "|"
	fi
}

stop_server()
{
	if find_server; then
		echo "|"
		echo -n "| $DESC: Stopping ... "
		kill `find_server |awk -F . '{print $1}'|awk '{print $1}'`
		echo "done."
		echo "|"
	else
		echo "|"
		echo "| Couldn't find a running $DESC"
		echo "|"
	fi
}

update_server()
{
	if find_server; then
		kill `find_server |awk -F . '{print $1}'|awk '{print $1}'`
		sleep 3
	fi

	steamcmd +login anonymous +force_install_dir $DIR/ +app_update 222860 validate +quit
}

print_status()
{
	if find_server; then
		echo "|"
		echo "| $DESC online!"
		echo "|"
	else
		echo "|"
		echo "| $DESC offline!"
		echo "|"
	fi
}

show_console()
{
	if find_server; then
		echo "|"
		echo "| To exit the console, press Ctrl+A and Ctrl+D"
		echo "| To turn off the server, press Ctrl+D"
		echo "|"
		sleep 3
		screen -r $SCREENNAME
	else
		echo "|"
		echo "| Couldn't find a running $DESC"
		echo "|"
	fi
}

case "$ACTION" in
	start)
		run_server ;;

	stop)
		stop_server ;;

	restart)
		stop_server
		sleep 2
		run_server ;;

	status)
		print_status ;;

	console)
		show_console ;;

	update)
		update_server ;;

	*)
		echo "Use: $0 -a <start|stop|restart|status|update|console>"
		exit 1 ;;
esac

exit 0
